### PR TITLE
Inline templates

### PR DESCRIPTION
**Pull request by flashios09**
Inline templates:
- add template linting to inline templates inside js and ts files

image

- provide completions for inline templates inside js or ts files

image

### CODE REVIEW

**Review by lifeart — APPROVED** [review]

**Comment by lifeart** [comment]
@flashios09 thank you! https://marketplace.visualstudio.com/items?itemName=lifeart.vscode-ember-unstable 0.2.29 released

**Comment by andreyfel** [comment]
@flashios09 I tried the new version of language server and **All lines** in my integration tests were highlighted with errors including commented lines and js code.

Screenshot 2019-09-11 at 15 23 42

**Comment by flashios09** [comment]
> I tried the new version of language server and **All lines** in my integration tests were highlighted with errors including commented lines and js code.

@andreyfel can i see the code ?
BTW on vscode, i have the "**trim trailing whitespaces on save**" activated

**Comment by andreyfel** [comment]
That is regular code, nothing special. Every single line is highlighted with error. It seems not everyone has this issue. Maybe it is related to yarn workspace which we use? Will try it out next week.

**Comment by flashios09** [comment]
@andreyfel sorry, i don't have this error on my editor !
this is a screenshot for a generated test:
image

another screenshot for inline template linting:
image

and the last one for completion:
image

**Pull request merged**
