### PR TITLE
Enable running integration tests individually

### PR DESCRIPTION
**Pull request by saravanak**
Provides afterEach and beforeEach callbacks which will init and reload the projects everytime the tests are run.

Allows tests like `yarn run test -t 'returns the definition information for a component in a template'` to be run individually. 

The approach of calling `initialize` facilitates the setting up of the test fixture correctly for each run and we use `reloadProjects` command to reset the state after every run. 

No 'changes' on the snapshot file.

### CODE REVIEW

**Comment by saravanak** [comment]
I am not sure why the coverage reports are in red, from what I see in local, the coverage summary is `~=`.

**this branch**
```
=============================== Coverage summary ===============================                                                                                                              
Statements   : 64.51% ( 3658/5670 )                                                                                                                                                           
Branches     : 52.92% ( 1251/2364 )                                                                                                                                                           
Functions    : 69.79% ( 603/864 )                                                                                                                                                             
Lines        : 67.01% ( 1812/2704 )                                                                                                                                                           
================================================================================  
```

**Target branch**
```
=============================== Coverage summary ===============================
Statements   : 64.13% ( 3636/5670 )
Branches     : 52.75% ( 1247/2364 )
Functions    : 69.33% ( 599/864 )
Lines        : 66.57% ( 1800/2704 )
================================================================================

```

**Comment by saravanak** [comment]
Rearranged the files a bit, only wrapping initServer for tests that use `full-project`

Tests now:

```
  integration
    Initialize request
      ✓ returns an initialize request (1616ms)
->  With `full-project` initialized on server
      Completion request
        ✓ returns all components and helpers when requesting completion items in a handlebars expression (42ms)
        ✓ returns all angle-bracket in a element expression (23ms)
        ✓ returns all routes when requesting completion items in an inline link-to (19ms)
        ✓ returns all routes when requesting completion items in a block link-to (23ms)
      Definition request
        ✓ returns the definition information for a component in a template (31ms)
        ✓ returns the definition information for a helper in a template (17ms)
        ✓ returns the definition information for a hasMany relationship (70ms)
        ✓ returns the definition information for a belongsTo relationship (15ms)
        ✓ returns the definition information for a transform (19ms)
    Go to definition works for all supported cases
      ✓ to to route defintion from LinkTo component (12ms)
      ✓ go to local template-only component (6ms)
      ✓ go to local template-only component in module (6ms)
 //and so on..

```

But this causes a digger diff on snapshot file, though

**Comment by lifeart** [comment]
@saravanak let's have such cases in new file, to cover 2 cases 

1.) current case (to be sure we don't leak state between projects) 
2.) updated case (atomic usage)

**Comment by saravanak** [comment]
> 1.) current case (to be sure we don't leak state between projects)
2.) updated case (atomic usage)

So to be clear, you are saying that the cases dependent on `full-project` should be moved to a separate file and the rest (non changed) tests should remain in the current `integration-test.js` file @lifeart . Am I right ?

**Comment by saravanak** [comment]
> 1.) current case (to be sure we don't leak state between projects)
2.) updated case (atomic usage)

So to be clear, you are saying that the cases dependent on `full-project` initialization should be moved to a separate test file and the rest (non changed) tests should remain in the current `integration-test.js` file @lifeart . Am I right ?

**Comment by lifeart** [comment]
@saravanak not really, I mean land all new changes into new file and leave existing one "as-is" to have ability to track possible future regression/side-effects, related to projects overlap or such (if issue appears in server itself, not in addons).

**Comment by saravanak** [comment]
Have separated the files which use fixtures and which use the `broccoli` way of generating the fixtures @lifeart

**Review by lifeart — APPROVED** [review]

**Comment by lifeart** [comment]
@saravanak thank you!

**Pull request merged**
